on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: SSH 连接
        uses: tanst/debugger-action@master
      - name: Get dependencies
        run: make deps
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Build
        run: make build
      - name: 编译可执行文件
        run: |
            cd cmd
            go build -o frp-notify main.go
            mkdir frp-notify
            mv frp-notify ./frp-notify/
      - name: 上传 frp-notify
        uses: actions/upload-artifact@v2
        with:
          name: frp-notify
          path: ./cmd/frp-notify/
